resolver: lts-19.4
packages:
- .

ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies

extra-deps:
- fdo-notify-0.3.1@sha256:9cfb75a5a0d5e4b1d40b0b4dbcc6bb29e58f21e4e14c83e2ffe1ca78bdee59d8,734
- package-version-0.1.0.0@sha256:bb9fc93e905540aa8e1b32f80c2dc82756a4481c63779bd92e3796ed8085ab98,2854
- tomland-1.3.3.1@sha256:83a8fd26a97164100541f7b26aa40ffdc6f230b21e94cbb3eae1fb7093c4356e,8924
- validation-selective-0.1.0.1@sha256:9a5aa8b801efc6a4ffb120e1b28e80c5f7d090043be56bba11222cd20c393044,3621
- git: https://github.com/tbidne/algebra-simple.git
  commit: 2a020dbe0290abe57af31c5011a3a18ff17dcec9
- git: https://github.com/tbidne/byte-types.git
  commit: e1f2f889ede098b8c7682db1504a831f81c98c3d
- git: https://github.com/tbidne/pythia.git
  commit: 0b8977d67b1f7e8bb00560988f92455ed0ebc3a7
- git: https://github.com/tbidne/relative-time.git
  commit: 1b0a14bee427e7401247fd3d8279a54e0b5bd5ea
- git: https://github.com/tbidne/smart-math.git
  commit: f33aabe5eb9f6f5ae4d51607d7159086bcb9899d

allow-newer: true

nix:
  shell-file: nix/stack.nix
