resolver: lts-19.4
packages:
- .

ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies

extra-deps:
- fdo-notify-0.3.1@sha256:9cfb75a5a0d5e4b1d40b0b4dbcc6bb29e58f21e4e14c83e2ffe1ca78bdee59d8,734
- package-version-0.1.0.0@sha256:bb9fc93e905540aa8e1b32f80c2dc82756a4481c63779bd92e3796ed8085ab98,2854
- tomland-1.3.3.1@sha256:83a8fd26a97164100541f7b26aa40ffdc6f230b21e94cbb3eae1fb7093c4356e,8924
- validation-selective-0.1.0.1@sha256:9a5aa8b801efc6a4ffb120e1b28e80c5f7d090043be56bba11222cd20c393044,3621
- git: https://github.com/tbidne/algebra-simple.git
  commit: be105b31e3bd2bc00c69cd5c1e869294b26fbb17
- git: https://github.com/tbidne/byte-types.git
  commit: 60e7ad675f017cbd8467bef649cfcea48f626ab5
- git: https://github.com/tbidne/pythia.git
  commit: ea7dd618664012b5fa7bf59da62959057f5eb008
- git: https://github.com/tbidne/relative-time.git
  commit: dd4bf2a37bc22763eed6c9bf80ada9b323fb7a22
- git: https://github.com/tbidne/smart-math.git
  commit: 652cf1c7b61c1c8b67ce1ce1b4ecea77173b947a

allow-newer: true

nix:
  shell-file: nix/stack.nix
