resolver: nightly-2022-10-11
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
extra-deps:
- fdo-notify-0.3.1@sha256:9cfb75a5a0d5e4b1d40b0b4dbcc6bb29e58f21e4e14c83e2ffe1ca78bdee59d8,734
- package-version-0.1.0.0@sha256:bb9fc93e905540aa8e1b32f80c2dc82756a4481c63779bd92e3796ed8085ab98,2854
- toml-reader-0.1.0.0@sha256:66e2b4261739559e6d1be50391af7038610c3898bc748ce7985c4e4037b623ea,3559
- git: https://github.com/tbidne/algebra-simple.git
  commit: c8aaa4495964ecea9bb898c4fcb8b1c718ecc813
- git: https://github.com/tbidne/bounds.git
  commit: 7a8832ef4a55d565e72fab553a4d485329235bf7
- git: https://github.com/tbidne/byte-types.git
  commit: cc0e1323b51f1ec3441ddc6578a05e9d7fcdb977
- git: https://github.com/tbidne/monad-effects.git
  commit: e3fb642bb17981c8243c95148ba2350caff9063b
  subdirs:
  - monad-callstack
  - monad-fs
  - monad-ioref
  - monad-logger-namespace
  - monad-stm
  - monad-thread
  - monad-time
- git: https://github.com/tbidne/pythia.git
  commit: b8a942f5136ee247facb1e7be4749facd8939199
- git: https://github.com/tbidne/relative-time.git
  commit: dd4bf2a37bc22763eed6c9bf80ada9b323fb7a22
- git: https://github.com/tbidne/smart-math.git
  commit: 49c8269089372c989426b57ad0574ec0ef63bad0
- git: https://github.com/tbidne/time-conv.git
  commit: 02498efe9f6185bc14db55a6d0068c05a473b13f
nix:
  shell-file: nix/stack.nix
