resolver: nightly-2022-10-11
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
extra-deps:
- fdo-notify-0.3.1@sha256:9cfb75a5a0d5e4b1d40b0b4dbcc6bb29e58f21e4e14c83e2ffe1ca78bdee59d8,734
- package-version-0.1.0.0@sha256:bb9fc93e905540aa8e1b32f80c2dc82756a4481c63779bd92e3796ed8085ab98,2854
- toml-reader-0.1.0.0@sha256:66e2b4261739559e6d1be50391af7038610c3898bc748ce7985c4e4037b623ea,3559
- git: https://github.com/tbidne/algebra-simple.git
  commit: 2c8a79e8d3bf67c99e4851c557bf68a44c512307
- git: https://github.com/tbidne/bounds.git
  commit: 004f03aec46f29069fd0bf5115a384cd2b3141b3
- git: https://github.com/tbidne/byte-types.git
  commit: be3e764d76c530fd3641c133ed2d53adfc8f046d
- git: https://github.com/tbidne/monad-effects.git
  commit: 3fddc571755e7b01a0c665058e9e0503b5c07250
  subdirs:
  - monad-callstack
  - monad-fs
  - monad-ioref
  - monad-logger-namespace
  - monad-stm
  - monad-thread
  - monad-time
- git: https://github.com/tbidne/pythia.git
  commit: 6516603d692314b5ac2b18a6de242102e2ffa35e
- git: https://github.com/tbidne/relative-time.git
  commit: dd4bf2a37bc22763eed6c9bf80ada9b323fb7a22
- git: https://github.com/tbidne/smart-math.git
  commit: e88d85948eb7de24ebb567ca10e06257fc5dbd49
- git: https://github.com/tbidne/time-conv.git
  commit: 147a0b9f98e8bf558735cf49c63071564d11681f
nix:
  shell-file: nix/stack.nix
