poll-interval = 10

[logging]
severity = "debug"
location = "stdout"

[battery-percentage]
repeat-events = false
error-events = "no-repeats"

[[battery-percentage.alert]]
percent = 50
urgency = "low"

[[battery-percentage.alert]]
percent = 30
urgency = "normal"

[[battery-percentage.alert]]
percent = 20
urgency = "critical"

[[battery-percentage.alert]]
percent = 10
urgency = "critical"

[[battery-percentage.alert]]
percent = 5
urgency = "critical"

# Send alert when the current minute is even
[[single]]
poll-interval = 10
command = """
  min=`date +%M`;
  if [[ \"$min % 2\" -eq 0 ]]; then
    echo -n "true"
  else
    echo -n "false"
fi
"""
trigger = "true"

[single.note]
summary = "Even/Odd"
body = "We're even, yay!"
timeout = "10"

