note-system = "dbus"

[logging]
severity = "debug"
size-mode = "delete 100.5 mb"

[battery-percentage]
repeat-events = false
error-events = "no-repeats"
app = "sysfs"

[[battery-percentage.alert]]
percent = 50
urgency = "low"

[[battery-percentage.alert]]
percent = 30
urgency = "normal"

[[battery-percentage.alert]]
percent = 20
urgency = "critical"

[[battery-percentage.alert]]
percent = 10
urgency = "critical"

[[battery-percentage.alert]]
percent = 5
urgency = "critical"

# Send alert when the current minute is even
[[single]]
poll-interval = 10
command = """
  min=`date +%M`;
  if [[ \"$min % 2\" -eq 0 ]]; then
    echo -n "true"
  else
    echo -n "false"
  fi
"""
trigger = "true"

[single.note]
summary = "Even/Odd"
body = "We're even, yay!"
timeout = 10

# requires lm-sensors
[[single]]
command = """
  temp_res=$(sensors | head -n 3 | tail -n 1)
  regex="temp1:\\s*\\+([0-9]+)\\.[0-9]{0,2}°[C|F]"

  if [[ $temp_res =~ $regex ]]; then
    temp="${BASH_REMATCH[1]}"
    # not actually that hot...
    if [[ $temp -gt 20 ]]; then
      echo "true"
    else
      echo "false"
    fi
  else
    echo "couldn't parse: ${temp_res}"
    exit 1
  fi
"""
trigger = "true"

[single.note]
summary = "Temperature"
body = "We're hot!"
urgency = "critical"
timeout = 10

[[net-interface]]
app = "nmcli"
poll-interval = 30
device = "wifi-device"

[[net-interface]]
app = "nmcli"
poll-interval = 60
device = "eth-device"