note-system = "notify-send"

[logging]
severity = "debug"
location = "stdout"
size-mode = "warn 52 kilobytes"

[[single]]
name = "trivial-service"
poll-interval = 5
repeat-events = true
command = ""
trigger = ""

[single.note]
summary = "Trivial"
body = "We did nothing, yay!"
timeout = 2

