name: style

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/31ffc50c571e6683e9ecc9dbcbd4a8e9914b4497.tar.gz

      - name: cabal-fmt
        run: nix-shell shell.nix --command "bash ./ci_scripts/cabal-fmt.sh"

      - name: hlint
        run: nix-shell shell.nix --command "bash ./ci_scripts/hlint.sh"

      - name: ormolu
        run: nix-shell shell.nix --command "bash ./ci_scripts/ormolu.sh"

      - name: nixpkgs-fmt
        run: nix-shell shell.nix --command "bash ./ci_scripts/nixpkgs-fmt.sh"
